spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/school
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
   port: 9595